# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6120237d7e7616885d5612241839b05996907eee1d40a9859c6f50a7fce46d5345a4922f43597d5cb92a6b51ccfad3f29eff879819335ed28a0e11717c54c10b

test:
  secret_key_base: e4fb8442c1f361fb0d57d2b01c671603a497017553d5debd5673074294e4d428422e89ce4d48f0cba8e6ef16641d086789aa76f11fd5e1aa6396566998c4c69c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
